[package]
name = "github-func-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
flowsnet-platform-sdk = "0.1"
serde_json = "1.0.93"
slack-flows = "0.3"
tokio_wasi = { version = "1.25.0", features = ["macros", "rt"] }
dotenv = "0.15.0"
openai-flows = "0.7"